name: generate snake

on:
  schedule:
    - cron: "0 */24 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: Platane/snk/svg-only@v3
        with:
          github_user_name: juliank1m
          outputs: |
            dist/github-contribution-grid-snake-dark.svg?color_snake=%23D4C4F7&color_dots=%230d1117,%23FCDADA,%23F9C4C4,%23F5A8A8,%23F08C8C
            dist/github-contribution-grid-snake.svg

      - uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
